### ISSUE TITLE
bulk_delete_not_working 😢 

### ISSUE THREAD

**Issue by devinhanaway** [pocc/bulk_delete_notion_pages#1]
Hey there, saw this on a couple forum's and would have a lot of value in using it. Unfortunately when I follow the instructions on https://pocc.github.io/bulk_delete_notion_pages/ it doesn't work. Wondering if anyone who is a part of creating this might be willing to debug and push out a new release. Thanks a ton in advance 🙏

**Comment by pocc** [comment]
* You don't have enough information for a problem here, more than "it's not working". If you need help with bug report formatting, this Stack Overflow post has a bunch of templates: https://stackoverflow.com/questions/29416909/how-can-i-write-good-bug-reports
* This doesn't really solve a problem anyway because the pages are already deleted (per Notion's own documentation)
* I'll take PRs, but probably not issues
* I'll be closing this issue. If you want to resubmit an actual bug report, please provide data, screenshots, error messages, what you've tried so far, etc.
